[project]
authors = ["stano <>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Advent of Code 2024"
name = "aoc24"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
day_15 = "mojo run src/main.mojo 15 input/day15.txt"

build_for_tracing = "mojo build -g src/main.mojo"

trace = "sudo dtrace -c './main 11 input/day11.txt' -o out.stacks -n 'profile-997 /execname == \"main\"/ { @[ustack(100)] = count(); }'"

# E.g. have the cloned brendangregg/FlameGraph repo on your PATH
flamegraph = "stackcollapse.pl out.stacks | flamegraph.pl > flamegraph.svg"

profile = "magic run build_for_tracing; magic run trace; magic run flamegraph"

[dependencies]
max = ">=24.5.0,<25"
